# This docker compose will run the development container with redis in the same docker network together.
# The dev container must be built locally.
# Navigate to the root directory of the app and run `docker build -f docker/dev/Dockerfile -t receipt-wrangler-dev .`
# Then this docker compose will spin up a development environment
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data:/data
    networks:
      - app-net

  receipt-wrangler-dev:
    image: receipt-wrangler-dev:latest
    restart: always
    ports:
      - "9000:22"
    networks:
      - app-net
    volumes:
      - app:/app
      - docs:/docs
      - go:/go
      - root:/root
      - etc:/etc
      - usr:/usr
      - var:/var
      - opt:/opt

networks:
  app-net:

volumes:
  app:
  docs:
  go:
  root:
  etc:
  usr:
  var:
  opt:

