/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Command to delete the user\'s own account
 */
export interface DeleteAccountCommand { 
    /**
     * User\'s current password for confirmation
     */
    password: string;
}

